name: Jive Unit Tests
description: Run unit tests against a build package.

inputs:
  secrets:
    description: 'Any secrets necessary for the "test:unit" script to run'
    required: true

runs:
  using: composite
  steps:
    - name: Add Secrets to Env
      shell: bash
      env:
        SECRETS_JSON: ${{ inputs.secrets }}
      run: |
        bun run - <<'BUN'
          const STEP = "unit-tests";
          // TODO: move action to its own CLI rather than using composite
          if (typeof process.env.SECRETS_JSON === "string") {
            console.log(`::add-mask::${process.env.SECRETS_JSON}`);
          }
          const secrets = JSON.parse(process.env.SECRETS_JSON || "{}");
          for (const value of Object.values(secrets)) {
            if (value) console.log(`::add-mask::${value}`);
          }
          const requiredSecrets = require('./package.json')?.jive?.requiredSecrets?.[STEP] ?? [];
          const secretsToPass = {};
          const missingSecrets = [];
          for (const requiredSecret of requiredSecrets) {
            if (requiredSecret in secrets) {
              secretsToPass[requiredSecret] = secrets[requiredSecret];
            } else {
              missingSecrets.push(requiredSecret);
            }
          }
          if (missingSecrets.length > 0) {
            console.log(`Missing the following secrets (required for ${STEP}: ${missingSecrets.join(", ")}`);
            process.exit(1);
          }
          for (const [key, value] of Object.entries(secretsToPass)) {
            require("fs").appendFileSync(process.env.GITHUB_ENV, `${key}=${value}\n`);
          }
        BUN
    - name: Run Unit Tests
      shell: bash
      run: |
        bun run test:unit
