FROM alpine:3.21 as gcc
RUN apk add build-base
FROM scratch
COPY --from=gcc /usr/bin /usr/bin
COPY --from=gcc /usr/lib /usr/lib
COPY --from=gcc /usr/libexec /usr/libexec
COPY --from=gcc /lib/ld-musl-x86_64.so.1 /lib/ld-musl-x86_64.so.1