name: Build & Deploy Apps

on:
  push:
    branches:
      - main
    paths:
      - 'packages/apps/**'
      - '.github/workflows/application.yml'

jobs:
  compute-apps-to-rebuild:
    runs-on: ubuntu-latest
    outputs:
      changed-apps: ${{ steps.get-changed-apps.outputs.changed-apps }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Needed to get analyze the latest commit (if any images changed)
          fetch-depth: 2

      - name: Get Changed Apps
        id: get-changed-apps
        run: |
          shopt -s expand_aliases
          source ./startup.sh
          chaine cicd packages apps

  build-and-deploy-apps:
    needs: compute-apps-to-rebuild
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.compute-apps-to-rebuild.outputs.changed-apps) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build & Deploy Website
        env:
          PUBLISH_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          shopt -s expand_aliases
          source ./startup.sh
          chaine dev @chaine-app/${{ matrix.app }} deps install
          chaine dev @chaine-app/${{ matrix.app }} build
          chaine dev @chaine-app/${{ matrix.app }} publish
          chaine dev @chaine-app/${{ matrix.app }} deploy
