name: Build & Deploy Apps

on:
  push:
    branches:
      - main
    paths:
      - 'packages/apps/**'

jobs:
  build-apps:
    runs-on: ubuntu-latest
    steps:
      - name: no-op
        run: echo 'hello world'

  deploy-websites:
    runs-on: ubuntu-latest
    steps:
      - name: no-op
        run: echo 'hello world'

  deploy-mobile-apps:
    runs-on: ubuntu-latest
    steps:
      - name: no-op
        run: echo 'hello world'
