name: Publish Commands

on:
  push:
    branches:
      - main
    paths:
      - 'packages/cmds/**'

jobs:
  publish-command:
    runs-on: ubuntu-latest
    steps:
      - name: no-op
        run: echo 'hello world'
