name: Build & Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - '.github/workflows/docker.yml'

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Needed to get analyze the latest commit (if any images changed)
          fetch-depth: 2

      - name: Login To Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install CI CLI Dependencies
        run: cd ./packages/cmds/chaine && npx --quiet pnpm install

      - name: Build Images
        run: npx --quiet tsx ./packages/cmds/chaine/src/index.tsx cicd docker

  # TODO: implement. If the underlying dockerfile changes, the services must redeploy
  # redeploy-all-services