name: Build & Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - '.github/workflows/docker.yml'

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Needed to get analyze the latest commit (if any images changed)
          fetch-depth: 2

      - name: Login To Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Images
        run: |
          shopt -s expand_aliases
          source ./startup.sh
          chaine cicd docker

  # TODO: implement. If the underlying dockerfile changes, the services must redeploy
  # redeploy-all-services
