name: CI/CD

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  pipeline:
    name: Pipeline
    uses: ./.github/workflows/reusable-pipeline.yml
    secrets: inherit
    with:
      environments: Production
      preview-deploys: true
      publish: true
