name: Build & Deploy Services

on:
  push:
    branches:
      - main
    paths:
      - 'packages/svcs/**'

jobs:
  build-services:
    runs-on: ubuntu-latest
    steps:
      - name: no-op
        run: echo 'hello world'

  push-service-packages:
    runs-on: ubuntu-latest
    steps:
      - name: no-op
        run: echo 'hello world'

  redeploy-services:
    runs-on: ubuntu-latest
    steps:
      - name: no-op
        run: echo 'hello world'